/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfluencerIndexRouteImport } from './routes/influencer.index'
import { Route as BrowseIndexRouteImport } from './routes/browse.index'
import { Route as InfluencerStatusRouteImport } from './routes/influencer.status'
import { Route as InfluencerOnboardingRouteImport } from './routes/influencer.onboarding'
import { Route as BusinessIdRouteImport } from './routes/business.$id'
import { Route as BrowseCategoryRouteImport } from './routes/browse.$category'
import { Route as AuthenticatedPostRequirementRouteImport } from './routes/_authenticated/post-requirement'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardSavedRouteImport } from './routes/_authenticated/dashboard/saved'
import { Route as AuthenticatedDashboardRequirementsRouteImport } from './routes/_authenticated/dashboard/requirements'
import { Route as AuthenticatedDashboardFindInfluencerRouteImport } from './routes/_authenticated/dashboard/find-influencer'
import { Route as AuthenticatedDashboardChatsRouteImport } from './routes/_authenticated/dashboard/chats'
import { Route as AuthenticatedBusinessSetupStaffRouteImport } from './routes/_authenticated/business/setup-staff'
import { Route as AuthenticatedBusinessOnboardingRouteImport } from './routes/_authenticated/business/onboarding'
import { Route as AuthenticatedAdminInfluencerApprovalsRouteImport } from './routes/_authenticated/admin/influencer-approvals'
import { Route as AuthenticatedBusinessDashboardRouteRouteImport } from './routes/_authenticated/business/dashboard/route'
import { Route as AuthenticatedBusinessDashboardIndexRouteImport } from './routes/_authenticated/business/dashboard/index'
import { Route as AuthenticatedBusinessDashboardRequirementsRouteImport } from './routes/_authenticated/business/dashboard/requirements'
import { Route as AuthenticatedBusinessDashboardProfileRouteImport } from './routes/_authenticated/business/dashboard/profile'
import { Route as AuthenticatedBusinessDashboardProductsRouteImport } from './routes/_authenticated/business/dashboard/products'
import { Route as AuthenticatedBusinessDashboardLeadsRouteImport } from './routes/_authenticated/business/dashboard/leads'
import { Route as AuthenticatedBusinessDashboardFeaturedRouteImport } from './routes/_authenticated/business/dashboard/featured'
import { Route as AuthenticatedBusinessDashboardBillingRouteImport } from './routes/_authenticated/business/dashboard/billing'
import { Route as AuthenticatedBusinessDashboardAppointmentsRouteImport } from './routes/_authenticated/business/dashboard/appointments'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerIndexRoute = InfluencerIndexRouteImport.update({
  id: '/influencer/',
  path: '/influencer/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerStatusRoute = InfluencerStatusRouteImport.update({
  id: '/influencer/status',
  path: '/influencer/status',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerOnboardingRoute = InfluencerOnboardingRouteImport.update({
  id: '/influencer/onboarding',
  path: '/influencer/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseCategoryRoute = BrowseCategoryRouteImport.update({
  id: '/browse/$category',
  path: '/browse/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostRequirementRoute =
  AuthenticatedPostRequirementRouteImport.update({
    id: '/post-requirement',
    path: '/post-requirement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSavedRoute =
  AuthenticatedDashboardSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRequirementsRoute =
  AuthenticatedDashboardRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardFindInfluencerRoute =
  AuthenticatedDashboardFindInfluencerRouteImport.update({
    id: '/find-influencer',
    path: '/find-influencer',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardChatsRoute =
  AuthenticatedDashboardChatsRouteImport.update({
    id: '/chats',
    path: '/chats',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedBusinessSetupStaffRoute =
  AuthenticatedBusinessSetupStaffRouteImport.update({
    id: '/business/setup-staff',
    path: '/business/setup-staff',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessOnboardingRoute =
  AuthenticatedBusinessOnboardingRouteImport.update({
    id: '/business/onboarding',
    path: '/business/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInfluencerApprovalsRoute =
  AuthenticatedAdminInfluencerApprovalsRouteImport.update({
    id: '/influencer-approvals',
    path: '/influencer-approvals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardRouteRoute =
  AuthenticatedBusinessDashboardRouteRouteImport.update({
    id: '/business/dashboard',
    path: '/business/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardIndexRoute =
  AuthenticatedBusinessDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBusinessDashboardRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardRequirementsRoute =
  AuthenticatedBusinessDashboardRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => AuthenticatedBusinessDashboardRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardProfileRoute =
  AuthenticatedBusinessDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedBusinessDashboardRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardProductsRoute =
  AuthenticatedBusinessDashboardProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedBusinessDashboardRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardLeadsRoute =
  AuthenticatedBusinessDashboardLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedBusinessDashboardRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardFeaturedRoute =
  AuthenticatedBusinessDashboardFeaturedRouteImport.update({
    id: '/featured',
    path: '/featured',
    getParentRoute: () => AuthenticatedBusinessDashboardRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardBillingRoute =
  AuthenticatedBusinessDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedBusinessDashboardRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardAppointmentsRoute =
  AuthenticatedBusinessDashboardAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedBusinessDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/post-requirement': typeof AuthenticatedPostRequirementRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/business/$id': typeof BusinessIdRoute
  '/influencer/onboarding': typeof InfluencerOnboardingRoute
  '/influencer/status': typeof InfluencerStatusRoute
  '/browse/': typeof BrowseIndexRoute
  '/influencer/': typeof InfluencerIndexRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRouteRouteWithChildren
  '/admin/influencer-approvals': typeof AuthenticatedAdminInfluencerApprovalsRoute
  '/business/onboarding': typeof AuthenticatedBusinessOnboardingRoute
  '/business/setup-staff': typeof AuthenticatedBusinessSetupStaffRoute
  '/dashboard/chats': typeof AuthenticatedDashboardChatsRoute
  '/dashboard/find-influencer': typeof AuthenticatedDashboardFindInfluencerRoute
  '/dashboard/requirements': typeof AuthenticatedDashboardRequirementsRoute
  '/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/business/dashboard/appointments': typeof AuthenticatedBusinessDashboardAppointmentsRoute
  '/business/dashboard/billing': typeof AuthenticatedBusinessDashboardBillingRoute
  '/business/dashboard/featured': typeof AuthenticatedBusinessDashboardFeaturedRoute
  '/business/dashboard/leads': typeof AuthenticatedBusinessDashboardLeadsRoute
  '/business/dashboard/products': typeof AuthenticatedBusinessDashboardProductsRoute
  '/business/dashboard/profile': typeof AuthenticatedBusinessDashboardProfileRoute
  '/business/dashboard/requirements': typeof AuthenticatedBusinessDashboardRequirementsRoute
  '/business/dashboard/': typeof AuthenticatedBusinessDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/post-requirement': typeof AuthenticatedPostRequirementRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/business/$id': typeof BusinessIdRoute
  '/influencer/onboarding': typeof InfluencerOnboardingRoute
  '/influencer/status': typeof InfluencerStatusRoute
  '/browse': typeof BrowseIndexRoute
  '/influencer': typeof InfluencerIndexRoute
  '/admin/influencer-approvals': typeof AuthenticatedAdminInfluencerApprovalsRoute
  '/business/onboarding': typeof AuthenticatedBusinessOnboardingRoute
  '/business/setup-staff': typeof AuthenticatedBusinessSetupStaffRoute
  '/dashboard/chats': typeof AuthenticatedDashboardChatsRoute
  '/dashboard/find-influencer': typeof AuthenticatedDashboardFindInfluencerRoute
  '/dashboard/requirements': typeof AuthenticatedDashboardRequirementsRoute
  '/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/business/dashboard/appointments': typeof AuthenticatedBusinessDashboardAppointmentsRoute
  '/business/dashboard/billing': typeof AuthenticatedBusinessDashboardBillingRoute
  '/business/dashboard/featured': typeof AuthenticatedBusinessDashboardFeaturedRoute
  '/business/dashboard/leads': typeof AuthenticatedBusinessDashboardLeadsRoute
  '/business/dashboard/products': typeof AuthenticatedBusinessDashboardProductsRoute
  '/business/dashboard/profile': typeof AuthenticatedBusinessDashboardProfileRoute
  '/business/dashboard/requirements': typeof AuthenticatedBusinessDashboardRequirementsRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/post-requirement': typeof AuthenticatedPostRequirementRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/business/$id': typeof BusinessIdRoute
  '/influencer/onboarding': typeof InfluencerOnboardingRoute
  '/influencer/status': typeof InfluencerStatusRoute
  '/browse/': typeof BrowseIndexRoute
  '/influencer/': typeof InfluencerIndexRoute
  '/_authenticated/business/dashboard': typeof AuthenticatedBusinessDashboardRouteRouteWithChildren
  '/_authenticated/admin/influencer-approvals': typeof AuthenticatedAdminInfluencerApprovalsRoute
  '/_authenticated/business/onboarding': typeof AuthenticatedBusinessOnboardingRoute
  '/_authenticated/business/setup-staff': typeof AuthenticatedBusinessSetupStaffRoute
  '/_authenticated/dashboard/chats': typeof AuthenticatedDashboardChatsRoute
  '/_authenticated/dashboard/find-influencer': typeof AuthenticatedDashboardFindInfluencerRoute
  '/_authenticated/dashboard/requirements': typeof AuthenticatedDashboardRequirementsRoute
  '/_authenticated/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/business/dashboard/appointments': typeof AuthenticatedBusinessDashboardAppointmentsRoute
  '/_authenticated/business/dashboard/billing': typeof AuthenticatedBusinessDashboardBillingRoute
  '/_authenticated/business/dashboard/featured': typeof AuthenticatedBusinessDashboardFeaturedRoute
  '/_authenticated/business/dashboard/leads': typeof AuthenticatedBusinessDashboardLeadsRoute
  '/_authenticated/business/dashboard/products': typeof AuthenticatedBusinessDashboardProductsRoute
  '/_authenticated/business/dashboard/profile': typeof AuthenticatedBusinessDashboardProfileRoute
  '/_authenticated/business/dashboard/requirements': typeof AuthenticatedBusinessDashboardRequirementsRoute
  '/_authenticated/business/dashboard/': typeof AuthenticatedBusinessDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cities'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/dashboard'
    | '/post-requirement'
    | '/browse/$category'
    | '/business/$id'
    | '/influencer/onboarding'
    | '/influencer/status'
    | '/browse/'
    | '/influencer/'
    | '/business/dashboard'
    | '/admin/influencer-approvals'
    | '/business/onboarding'
    | '/business/setup-staff'
    | '/dashboard/chats'
    | '/dashboard/find-influencer'
    | '/dashboard/requirements'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/business/dashboard/appointments'
    | '/business/dashboard/billing'
    | '/business/dashboard/featured'
    | '/business/dashboard/leads'
    | '/business/dashboard/products'
    | '/business/dashboard/profile'
    | '/business/dashboard/requirements'
    | '/business/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cities'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/post-requirement'
    | '/browse/$category'
    | '/business/$id'
    | '/influencer/onboarding'
    | '/influencer/status'
    | '/browse'
    | '/influencer'
    | '/admin/influencer-approvals'
    | '/business/onboarding'
    | '/business/setup-staff'
    | '/dashboard/chats'
    | '/dashboard/find-influencer'
    | '/dashboard/requirements'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/business/dashboard/appointments'
    | '/business/dashboard/billing'
    | '/business/dashboard/featured'
    | '/business/dashboard/leads'
    | '/business/dashboard/products'
    | '/business/dashboard/profile'
    | '/business/dashboard/requirements'
    | '/business/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cities'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/post-requirement'
    | '/browse/$category'
    | '/business/$id'
    | '/influencer/onboarding'
    | '/influencer/status'
    | '/browse/'
    | '/influencer/'
    | '/_authenticated/business/dashboard'
    | '/_authenticated/admin/influencer-approvals'
    | '/_authenticated/business/onboarding'
    | '/_authenticated/business/setup-staff'
    | '/_authenticated/dashboard/chats'
    | '/_authenticated/dashboard/find-influencer'
    | '/_authenticated/dashboard/requirements'
    | '/_authenticated/dashboard/saved'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/business/dashboard/appointments'
    | '/_authenticated/business/dashboard/billing'
    | '/_authenticated/business/dashboard/featured'
    | '/_authenticated/business/dashboard/leads'
    | '/_authenticated/business/dashboard/products'
    | '/_authenticated/business/dashboard/profile'
    | '/_authenticated/business/dashboard/requirements'
    | '/_authenticated/business/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CitiesRoute: typeof CitiesRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  BrowseCategoryRoute: typeof BrowseCategoryRoute
  BusinessIdRoute: typeof BusinessIdRoute
  InfluencerOnboardingRoute: typeof InfluencerOnboardingRoute
  InfluencerStatusRoute: typeof InfluencerStatusRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  InfluencerIndexRoute: typeof InfluencerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/': {
      id: '/influencer/'
      path: '/influencer'
      fullPath: '/influencer/'
      preLoaderRoute: typeof InfluencerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/status': {
      id: '/influencer/status'
      path: '/influencer/status'
      fullPath: '/influencer/status'
      preLoaderRoute: typeof InfluencerStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/onboarding': {
      id: '/influencer/onboarding'
      path: '/influencer/onboarding'
      fullPath: '/influencer/onboarding'
      preLoaderRoute: typeof InfluencerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$category': {
      id: '/browse/$category'
      path: '/browse/$category'
      fullPath: '/browse/$category'
      preLoaderRoute: typeof BrowseCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post-requirement': {
      id: '/_authenticated/post-requirement'
      path: '/post-requirement'
      fullPath: '/post-requirement'
      preLoaderRoute: typeof AuthenticatedPostRequirementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/saved': {
      id: '/_authenticated/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof AuthenticatedDashboardSavedRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/requirements': {
      id: '/_authenticated/dashboard/requirements'
      path: '/requirements'
      fullPath: '/dashboard/requirements'
      preLoaderRoute: typeof AuthenticatedDashboardRequirementsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/find-influencer': {
      id: '/_authenticated/dashboard/find-influencer'
      path: '/find-influencer'
      fullPath: '/dashboard/find-influencer'
      preLoaderRoute: typeof AuthenticatedDashboardFindInfluencerRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/chats': {
      id: '/_authenticated/dashboard/chats'
      path: '/chats'
      fullPath: '/dashboard/chats'
      preLoaderRoute: typeof AuthenticatedDashboardChatsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/business/setup-staff': {
      id: '/_authenticated/business/setup-staff'
      path: '/business/setup-staff'
      fullPath: '/business/setup-staff'
      preLoaderRoute: typeof AuthenticatedBusinessSetupStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/onboarding': {
      id: '/_authenticated/business/onboarding'
      path: '/business/onboarding'
      fullPath: '/business/onboarding'
      preLoaderRoute: typeof AuthenticatedBusinessOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/influencer-approvals': {
      id: '/_authenticated/admin/influencer-approvals'
      path: '/influencer-approvals'
      fullPath: '/admin/influencer-approvals'
      preLoaderRoute: typeof AuthenticatedAdminInfluencerApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/business/dashboard': {
      id: '/_authenticated/business/dashboard'
      path: '/business/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/dashboard/': {
      id: '/_authenticated/business/dashboard/'
      path: '/'
      fullPath: '/business/dashboard/'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedBusinessDashboardRouteRoute
    }
    '/_authenticated/business/dashboard/requirements': {
      id: '/_authenticated/business/dashboard/requirements'
      path: '/requirements'
      fullPath: '/business/dashboard/requirements'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardRequirementsRouteImport
      parentRoute: typeof AuthenticatedBusinessDashboardRouteRoute
    }
    '/_authenticated/business/dashboard/profile': {
      id: '/_authenticated/business/dashboard/profile'
      path: '/profile'
      fullPath: '/business/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedBusinessDashboardRouteRoute
    }
    '/_authenticated/business/dashboard/products': {
      id: '/_authenticated/business/dashboard/products'
      path: '/products'
      fullPath: '/business/dashboard/products'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardProductsRouteImport
      parentRoute: typeof AuthenticatedBusinessDashboardRouteRoute
    }
    '/_authenticated/business/dashboard/leads': {
      id: '/_authenticated/business/dashboard/leads'
      path: '/leads'
      fullPath: '/business/dashboard/leads'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardLeadsRouteImport
      parentRoute: typeof AuthenticatedBusinessDashboardRouteRoute
    }
    '/_authenticated/business/dashboard/featured': {
      id: '/_authenticated/business/dashboard/featured'
      path: '/featured'
      fullPath: '/business/dashboard/featured'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardFeaturedRouteImport
      parentRoute: typeof AuthenticatedBusinessDashboardRouteRoute
    }
    '/_authenticated/business/dashboard/billing': {
      id: '/_authenticated/business/dashboard/billing'
      path: '/billing'
      fullPath: '/business/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedBusinessDashboardRouteRoute
    }
    '/_authenticated/business/dashboard/appointments': {
      id: '/_authenticated/business/dashboard/appointments'
      path: '/appointments'
      fullPath: '/business/dashboard/appointments'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardAppointmentsRouteImport
      parentRoute: typeof AuthenticatedBusinessDashboardRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminInfluencerApprovalsRoute: typeof AuthenticatedAdminInfluencerApprovalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminInfluencerApprovalsRoute:
      AuthenticatedAdminInfluencerApprovalsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardChatsRoute: typeof AuthenticatedDashboardChatsRoute
  AuthenticatedDashboardFindInfluencerRoute: typeof AuthenticatedDashboardFindInfluencerRoute
  AuthenticatedDashboardRequirementsRoute: typeof AuthenticatedDashboardRequirementsRoute
  AuthenticatedDashboardSavedRoute: typeof AuthenticatedDashboardSavedRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardChatsRoute: AuthenticatedDashboardChatsRoute,
    AuthenticatedDashboardFindInfluencerRoute:
      AuthenticatedDashboardFindInfluencerRoute,
    AuthenticatedDashboardRequirementsRoute:
      AuthenticatedDashboardRequirementsRoute,
    AuthenticatedDashboardSavedRoute: AuthenticatedDashboardSavedRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedBusinessDashboardRouteRouteChildren {
  AuthenticatedBusinessDashboardAppointmentsRoute: typeof AuthenticatedBusinessDashboardAppointmentsRoute
  AuthenticatedBusinessDashboardBillingRoute: typeof AuthenticatedBusinessDashboardBillingRoute
  AuthenticatedBusinessDashboardFeaturedRoute: typeof AuthenticatedBusinessDashboardFeaturedRoute
  AuthenticatedBusinessDashboardLeadsRoute: typeof AuthenticatedBusinessDashboardLeadsRoute
  AuthenticatedBusinessDashboardProductsRoute: typeof AuthenticatedBusinessDashboardProductsRoute
  AuthenticatedBusinessDashboardProfileRoute: typeof AuthenticatedBusinessDashboardProfileRoute
  AuthenticatedBusinessDashboardRequirementsRoute: typeof AuthenticatedBusinessDashboardRequirementsRoute
  AuthenticatedBusinessDashboardIndexRoute: typeof AuthenticatedBusinessDashboardIndexRoute
}

const AuthenticatedBusinessDashboardRouteRouteChildren: AuthenticatedBusinessDashboardRouteRouteChildren =
  {
    AuthenticatedBusinessDashboardAppointmentsRoute:
      AuthenticatedBusinessDashboardAppointmentsRoute,
    AuthenticatedBusinessDashboardBillingRoute:
      AuthenticatedBusinessDashboardBillingRoute,
    AuthenticatedBusinessDashboardFeaturedRoute:
      AuthenticatedBusinessDashboardFeaturedRoute,
    AuthenticatedBusinessDashboardLeadsRoute:
      AuthenticatedBusinessDashboardLeadsRoute,
    AuthenticatedBusinessDashboardProductsRoute:
      AuthenticatedBusinessDashboardProductsRoute,
    AuthenticatedBusinessDashboardProfileRoute:
      AuthenticatedBusinessDashboardProfileRoute,
    AuthenticatedBusinessDashboardRequirementsRoute:
      AuthenticatedBusinessDashboardRequirementsRoute,
    AuthenticatedBusinessDashboardIndexRoute:
      AuthenticatedBusinessDashboardIndexRoute,
  }

const AuthenticatedBusinessDashboardRouteRouteWithChildren =
  AuthenticatedBusinessDashboardRouteRoute._addFileChildren(
    AuthenticatedBusinessDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedPostRequirementRoute: typeof AuthenticatedPostRequirementRoute
  AuthenticatedBusinessDashboardRouteRoute: typeof AuthenticatedBusinessDashboardRouteRouteWithChildren
  AuthenticatedBusinessOnboardingRoute: typeof AuthenticatedBusinessOnboardingRoute
  AuthenticatedBusinessSetupStaffRoute: typeof AuthenticatedBusinessSetupStaffRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedPostRequirementRoute: AuthenticatedPostRequirementRoute,
  AuthenticatedBusinessDashboardRouteRoute:
    AuthenticatedBusinessDashboardRouteRouteWithChildren,
  AuthenticatedBusinessOnboardingRoute: AuthenticatedBusinessOnboardingRoute,
  AuthenticatedBusinessSetupStaffRoute: AuthenticatedBusinessSetupStaffRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CitiesRoute: CitiesRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  BrowseCategoryRoute: BrowseCategoryRoute,
  BusinessIdRoute: BusinessIdRoute,
  InfluencerOnboardingRoute: InfluencerOnboardingRoute,
  InfluencerStatusRoute: InfluencerStatusRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  InfluencerIndexRoute: InfluencerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
