// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { createBrowserClient } from '@supabase/ssr';
import type { Database } from './types';

// A business's own site lives on a subdomain (e.g. some-business.luvlit.in) — a different origin
// from luvlit.in itself, so browser storage (localStorage) never carries a signed-in customer's
// session over automatically. Cookies scoped to the parent domain do. Only share the cookie
// across *.luvlit.in in production; localhost and *.vercel.app preview deployments keep an
// ordinary host-only cookie, same convention as businessSlugFromHostname() in public.functions.ts.
function sharedCookieDomain(): string | undefined {
  if (typeof window === 'undefined') return undefined;
  return /(^|\.)luvlit\.in$/.test(window.location.hostname) ? '.luvlit.in' : undefined;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Set these in your environment configuration.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // createBrowserClient reads/writes document.cookie directly and isn't meant to run outside a
  // browser — server-side rendering keeps the original supabase-js client (storage: undefined,
  // exactly as before; nothing is persisted server-side either way).
  if (typeof window === 'undefined') {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: undefined,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  }

  const domain = sharedCookieDomain();
  return createBrowserClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    cookieOptions: {
      path: '/',
      sameSite: 'lax',
      secure: window.location.protocol === 'https:',
      ...(domain ? { domain } : {}),
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

